name: Go Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ticket-reserve-api

    steps:
    # 1. GitHubからコードをダウンロードしてくる
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. ロボットの中にGo言語の環境をセットアップする
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    # 3. 実際にビルド（コンパイル）できるかテストする！
    - name: Build
      run: go build -v ./...
    
    - name: Vet
      run: go vet ./...
